blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import BlogView, BlogCreateView, BlogDetailView, BlogUpdateView, BlogDeleteView, toggle_published

app_name = BlogConfig.name

urlpatterns = [
    path('', BlogView.as_view(), name='home'),
    path('record/new/', BlogCreateView.as_view(), name='create_record'),
    path('view/<int:pk>/', cache_page(60)(BlogDetailView.as_view()), name='view_record'),
    path('edit/<int:pk>/', BlogUpdateView.as_view(), name='edit_record'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='delete_record'),
    path('published/<int:pk>/', toggle_published, name='change_published'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('e_mail_app.urls'), name='e_mail_app'),
    path('users/', include('users.urls'), name='users'),
    path('blog/', include('blog.urls'), name='blog')
]

e_mail_app/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from e_mail_app.apps import EMailAppConfig
from e_mail_app.views import MailingListView, MailingCreateView, MailingDetailView, MailingUpdateView, \
    MailingDeleteView, ClientListView, ClientDetailView, ClientCreateView, \
    ClientUpdateView, ClientDeleteView, settings_toggle_active, SettingsListView, SettingsDetailView, \
    SettingsUpdateView, SettingsCreateView, SettingsDeleteView

app_name = EMailAppConfig.name

urlpatterns = [
    path('', MailingListView.as_view(), name='home'),
    path('mailing/new', MailingCreateView.as_view(), name='create_mailing'),
    path('mailing/view/<int:pk>', cache_page(60)(MailingDetailView.as_view()), name='view_mailing'),
    path('mailing/edit/<int:pk>', MailingUpdateView.as_view(), name='update_mailing'),
    path('mailing/delete/<int:pk>', MailingDeleteView.as_view(), name='delete_mailing'),
    path('clients/', ClientListView.as_view(), name='client_home'),
    path('client/view/<int:pk>', cache_page(60)(ClientDetailView.as_view()), name='client_detail'),
    path('client/new/', ClientCreateView.as_view(), name='create_client'),
    path('client/edit/<int:pk>', ClientUpdateView.as_view(), name='update_client'),
    path('client/delete/<int:pk>', ClientDeleteView.as_view(), name='delete_client'),
    path('settings/', SettingsListView.as_view(), name='settings_home'),
    path('settings/new/', SettingsCreateView.as_view(), name='create_settings'),
    path('settings/view/<int:pk>', cache_page(60)(SettingsDetailView.as_view()), name='detail_settings'),
    path('settings/edit/<int:pk>', SettingsUpdateView.as_view(), name='edit_settings'),
    path('settings/delete/<int:pk>', SettingsDeleteView.as_view(), name='delete_settings'),
    path('settings/active/<int:pk>', settings_toggle_active, name='activate_settings'),
]

e_mail_app/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone

NULLABLE = {'blank': True, 'null': True}

LOG_CHOICES = (
    (True, 'Успешно'),
    (False, 'Неудача'),
)


class Client(models.Model):
    email = models.EmailField(verbose_name='Почта', unique=True)
    first_name = models.CharField(max_length=10, verbose_name='Имя')
    last_name = models.CharField(max_length=10, verbose_name='Фамилия')
    patronymic = models.CharField(max_length=20, verbose_name='Отчество', **NULLABLE)
    description = models.TextField(verbose_name='Описание', **NULLABLE)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL,
                              verbose_name='Владелец клиента', **NULLABLE)

    def __str__(self):
        return f'{self.email}: ({self.first_name}, {self.last_name}, {self.description})'

    class Meta:
        verbose_name = 'Клиент'
        verbose_name_plural = 'Клиенты'


class MailingMessage(models.Model):
    subject = models.CharField(max_length=100, verbose_name='Тема письма')
    message = models.TextField(verbose_name='Текст письма')
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL,
                              verbose_name='Владелец письма', **NULLABLE)

    def __str__(self):
        return f'{self.subject}; {self.message}'

    class Meta:
        verbose_name = 'Сообщение'
        verbose_name_plural = 'Сообщения'


class MailingSettings(models.Model):
    period_variants = (
        ('per_day', 'раз в день'),
        ('per_week', 'раз в неделю'),
        ('per_month', 'раз в месяц')
    )
    status_variants = (
        ('created', 'создана'),
        ('executing', 'запущена'),
        ('finished', 'закончена успешно'),
        ('error', 'законечена с ошибками')
    )
    mailing_name = models.CharField(max_length=50, verbose_name='Название рассылки', default='mailing_name')
    client = models.ManyToManyField(Client, verbose_name='Получатель')
    mail = models.ForeignKey(MailingMessage, on_delete=models.CASCADE)
    period = models.CharField(max_length=12, default='per_month', choices=period_variants,
                              verbose_name='Периодичность рассылки')
    status = models.CharField(max_length=15, choices=status_variants, default='created', verbose_name='Статус рассылки')
    start_time = models.DateTimeField(default=timezone.now, verbose_name='Начало рассылки')
    end_time = models.DateTimeField(default=timezone.now, verbose_name='Конец рассылки')
    next_date = models.DateTimeField(default=timezone.now, verbose_name='Дата следующей рассылки')
    is_active = models.BooleanField(default=False, verbose_name='Активна')
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL,
                              verbose_name='Владелец рассылки', **NULLABLE)

    def __str__(self):
        return f'{self.client}: ({self.start_time} - {self.end_time}; {self.status})'

    class Meta:
        verbose_name = 'Настройка'
        verbose_name_plural = 'Настройки'
        permissions = [
            (
                'toggle_active',
                'выключить рассылку'
            ),
        ]


class Logger(models.Model):
    mailing = models.ForeignKey(MailingSettings, on_delete=models.CASCADE, verbose_name='Рассылка', **NULLABLE)
    last_time_sending = models.DateTimeField(auto_now=True, verbose_name='Время рассылки', **NULLABLE)
    status = models.CharField(default=False, max_length=30, choices=LOG_CHOICES, verbose_name='Попытка', **NULLABLE)

    def __str__(self):
        return f'{self.last_time_sending} - {self.status}'

    class Meta:
        verbose_name = 'лог'
        verbose_name_plural = 'логи'

e_mail_app/forms.py
from django import forms

from e_mail_app.models import MailingMessage, Client, MailingSettings

WORDS_BLACKLIST = ('казино', 'криптовалюта', 'крипта', 'биржа', 'наркотики' 'бесплатно',
                   'обман', 'полиция', 'терракт')


class MailingAddForm(forms.ModelForm):

    class Meta:
        model = MailingMessage
        exclude = ('owner', )

    def clean_subject(self):
        cleaned_data = self.cleaned_data.get('subject')

        if cleaned_data in WORDS_BLACKLIST:
            raise forms.ValidationError('У-пс, тема письма в списке запрещённых товаров')

        return cleaned_data

    def clean_message(self):
        cleaned_data = self.cleaned_data.get('message')

        if cleaned_data in WORDS_BLACKLIST:
            raise forms.ValidationError('У-пс, письмо содержит в себе слова из списка'
                                        'запрещённых слов')

        return cleaned_data


class ClientAddForm(forms.ModelForm):

    class Meta:
        model = Client
        fields = '__all__'

    def clean_description(self):
        cleaned_data = self.cleaned_data.get('description')

        if cleaned_data in WORDS_BLACKLIST:
            raise forms.ValidationError('У-пс, описание клиента содержит в себе слова из списка'
                                        'запрещённых слов')

        return cleaned_data


class SettingsAddForm(forms.ModelForm):
    class Meta:
        model = MailingSettings
        exclude = ('status', 'owner')

    def clean_mailing_name(self):
        cleaned_data = self.cleaned_data.get('mailing_name')

        if cleaned_data in WORDS_BLACKLIST:
            raise forms.ValidationError('У-пс, название рассылки в списке запрещённых товаров')

        return cleaned_data


class SettingsManagerForm(forms.ModelForm):
    class Meta:
        model = MailingSettings
        exclude = ('status', 'owner', 'client')

    def clean_mailing_name(self):
        cleaned_data = self.cleaned_data.get('mailing_name')

        if cleaned_data in WORDS_BLACKLIST:
            raise forms.ValidationError('У-пс, название рассылки в списке запрещённых товаров')

        return cleaned_data

e_mail_app/views.py
from django.core.exceptions import PermissionDenied
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.forms import inlineformset_factory
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView

from e_mail_app.forms import MailingAddForm, ClientAddForm, SettingsAddForm, SettingsManagerForm
from e_mail_app.models import MailingMessage, Client, MailingSettings


# Create your views here.

class MailingListView(ListView):
    model = MailingMessage
    template_name = 'e_mail_app/e_mail_list.html'
    context_object_name = 'objects_list'


class MailingCreateView(CreateView):
    model = MailingMessage
    template_name = 'e_mail_app/e_mail_form.html'
    form_class = MailingAddForm
    success_url = reverse_lazy('e_mail_app:home')

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        settings_form_set = inlineformset_factory(MailingMessage, MailingSettings, form=SettingsAddForm, extra=1)
        if self.request.method == 'POST':
            context_data['formset'] = settings_form_set(self.request.POST, instance=self.object)
        else:
            context_data['formset'] = settings_form_set(instance=self.object)
        return context_data

    def form_valid(self, form):
        formset = self.get_context_data()['formset']
        mailing_template = form.save()
        self.object = form.save()
        self.object.owner = self.request.user
        mailing_template.owner = self.object.owner
        if formset.is_valid():
            formset.instance = self.object
            formset.save()
            mailing_template.save()
        return super().form_valid(form)


class MailingDetailView(DetailView):
    model = MailingMessage
    template_name = 'e_mail_app/e_mail_app_detail.html'
    context_object_name = 'objects_list'


class MailingUpdateView(UpdateView):
    model = MailingMessage
    template_name = 'e_mail_app/e_mail_update_form.html'
    form_class = MailingAddForm
    success_url = reverse_lazy('e_mail_app:home')
    perms = ('e_mail_app.view_mailingmessage', 'e_mail_app.view_mailingsettings', 'e_mail_app.toggle_active',
             'users.can_block', 'users.view_user')

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        settings_form_set = inlineformset_factory(MailingMessage, MailingSettings, form=SettingsAddForm, extra=1)
        if self.request.method == 'POST':
            context_data['formset'] = settings_form_set(self.request.POST, instance=self.object)
        else:
            context_data['formset'] = settings_form_set(instance=self.object)
        return context_data

    def form_valid(self, form):
        formset = self.get_context_data()['formset']
        mailing_template = form.save()
        self.object = form.save()
        self.object.owner = self.request.user
        mailing_template.owner = self.object.owner
        if formset.is_valid():
            formset.instance = self.object
            formset.save()
            mailing_template.save()
        return super().form_valid(form)

    def get_form_class(self):
        if self.request.user.is_staff or self.request.user.has_perms(perm_list=self.perms) \
                and not self.request.user.is_superuser:
            return SettingsManagerForm
        else:
            if self.request.user != self.get_object().owner:
                raise PermissionDenied
            else:
                return SettingsAddForm


class MailingDeleteView(DeleteView):
    model = MailingMessage
    template_name = 'e_mail_app/e_mail_app_confirm_delete.html'
    success_url = reverse_lazy('e_mail_app:home')


def settings_toggle_active(request, pk):
    mailing_item = get_object_or_404(MailingSettings, pk=pk)
    if mailing_item.is_active is True:
        mailing_item.is_active = False
    else:
        mailing_item.is_active = True
    mailing_item.save()
    return redirect(reverse('e_mail_app:settings_home'))


class ClientListView(ListView):
    model = Client
    template_name = 'clients/clients_list.html'
    context_object_name = 'objects_list'


class ClientDetailView(DetailView):
    model = Client
    template_name = 'clients/clients_detail.html'
    context_object_name = 'objects_list'


class ClientCreateView(CreateView):
    model = Client
    template_name = 'clients/clients_form.html'
    form_class = ClientAddForm
    success_url = reverse_lazy('e_mail_app:client_home')

    def form_valid(self, form):
        client = form.save()
        user = self.request.user
        client.owner = user
        client.save()
        return super().form_valid(form)


class ClientUpdateView(UpdateView):
    model = Client
    template_name = 'clients/clients_update_form.html'
    form_class = ClientAddForm
    success_url = reverse_lazy('e_mail_app:client_home')

    def form_valid(self, form):
        client = form.save()
        user = self.request.user
        client.owner = user
        client.save()
        return super().form_valid(form)


class ClientDeleteView(DeleteView):
    model = Client
    template_name = 'clients/clients_confirm_delete.html'
    success_url = reverse_lazy('e_mail_app:client_home')


class SettingsListView(ListView):
    model = MailingSettings
    template_name = 'mail_settings/settings_list.html'
    context_object_name = 'objects_list'


class SettingsDetailView(DetailView):
    model = MailingSettings
    template_name = 'mail_settings/settings_detail.html'
    context_object_name = 'objects_list'


class SettingsCreateView(CreateView):
    model = MailingSettings
    template_name = 'mail_settings/settings_add_form.html'
    form_class = SettingsAddForm
    success_url = reverse_lazy('e_mail_app:settings_home')

    def form_valid(self, form):
        mailing_settings = form.save()
        user = self.request.user
        mailing_settings.owner = user
        mailing_settings.save()
        return super().form_valid(form)


class SettingsUpdateView(UpdateView):
    model = MailingSettings
    template_name = 'mail_settings/settings_update_form.html'
    form_class = SettingsAddForm
    success_url = reverse_lazy('e_mail_app:settings_home')

    def form_valid(self, form):
        mailing_settings = form.save()
        user = self.request.user
        mailing_settings.owner = user
        mailing_settings.save()
        return super().form_valid(form)


class SettingsDeleteView(DeleteView):
    model = MailingSettings
    template_name = 'mail_settings/settings_confirm_delete.html'
    success_url = reverse_lazy('e_mail_app:settings_home')

e_mail_app/templates/mail_settings/settings_add_form.html
{% extends 'e_mail_app/base.html' %}
{% load static %}

{% block content %}
{% if user.is_blocked %}
<div class="col-12 text-center">
    <h1>
        Уважаемый пользователь, Ваш аккаунт заблокирован!
    </h1>
    <a class="p-2 btn btn-outline-primary" href="{% url 'users:logout' %}">Выйти</a>
</div>
{% else %}
<div class="container">
    <form method="post" action="" enctype="multipart/form-data" class="form-floating mx-auto">
        <div class="row ">
            <div class="col-12">
                <div class="col-10 mx-auto">
                <div class="card mb-4 box-shadow mx-auto">
                    <div class="card-header text-center">
                        <h4 class="my-0 font-weight-normal">Панель создания настроек</h4>
                    </div>
                    <div class="card-body text-center">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-block btn-outline-primary">Сохранить</button>
                        <a href="{% url 'e_mail_app:settings_home' %}" class="btn btn-block btn-outline-danger">Отмена</a>
                    </div>
                </div>
            </div>
            </div>
        </div>
    </form>
</div>
{% endif %}
{% endblock %}

e_mail_app/templates/mail_settings/settings_confirm_delete.html
{% extends 'e_mail_app/base.html' %}
{% load static %}

{% block content %}
{% if user.is_blocked %}
<div class="col-12 text-center">
    <h1>
        Уважаемый пользователь, Ваш аккаунт заблокирован!
    </h1>
    <a class="p-2 btn btn-outline-primary" href="{% url 'users:logout' %}">Выйти</a>
</div>
{% else %}

<div class="col-12">
  <div class="row">
    <div class="col-6">
      <div class="card">
        <div class="card-body">
          <form method="post">
            {% csrf_token %}
            <p>Хотите удалить настройки рассылке "{{object.mailing_name}}" ?</p>
            <button type="submit" class="btn btn-danger">Потвердить</button>
            <a href="{% url 'e_mail_app:home' %}" class="btn btn-warning">Отмена</a>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endif %}

{% endblock %}

e_mail_app/templates/mail_settings/settings_detail.html
{% extends 'e_mail_app/base.html' %}
{% load static %}

{% block content %}
{% if user.is_blocked %}
<div class="col-12 text-center">
    <h1>
        Уважаемый пользователь, Ваш аккаунт заблокирован!
    </h1>
    <a class="p-2 btn btn-outline-primary" href="{% url 'users:logout' %}">Выйти</a>
</div>
{% else %}
<div class="row">
    <div class="col-2 mx-auto">
        <div class="card mx-auto" style="width: 18rem;">
            <div class="card-body mx-20">
                <form method="post" enctype="multipart/form-data"></form>
                <h5 class="card-title">{{object.mailing_name}}</h5>
                <p class="card-text">Клиенты: {% for client in object.client.all %} {{client.email}} {% endfor %}</p>
                <p class="card-text">Периодичность отправки: {{object.period}}</p>
                <p class="card-text">Активна: {{object.is_active}}</p>
                <p class="card-text">Письмо: {{object.mail.message}}</p>
                <div class="col-12">
                    <div style="text-align:center">
                        {% if user == object.owner or user.is_superuser or perms.e_mail_app.edit_mailingsettings %}
                        <a href="{% url 'e_mail_app:edit_settings' object.pk %}" class="btn btn-md btn-outline-primary">Изменить</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endif %}
{% endblock %}

e_mail_app/templates/mail_settings/settings_list.html
{% extends 'e_mail_app/base.html' %}
{% load static %}

{% block content %}
{% if user.is_blocked %}
<div class="col-12 text-center">
    <h1>
        Уважаемый пользователь, Ваш аккаунт заблокирован!
    </h1>
    <a class="p-2 btn btn-outline-primary" href="{% url 'users:logout' %}">Выйти</a>
</div>
{% else %}

<main>
    <section class="py-5 text-center container">
        <div class="row py-lg-5">
            <div class="col-lg-6 col-md-8 mx-auto">
                <h1 class="fw-light">ЯРассылки</h1>
                <p class="lead text-body-secondary">Удобный сервис создания и отправки рассылок. Попробуй сейчас</p>
                <p>
                    {% if user.is_authenticated %}
                    <a href="{% url 'e_mail_app:create_settings' %}" class="btn btn-primary my-2">Создать настройки
                        рассылки</a>
                    {% else %}
                    <a href="{% url 'users:login' %}" class="btn btn-primary my-2">Создать настройки рассылки</a>
                    {% endif %}
                </p>
            </div>
        </div>
    </section>

    <h1 class="fw-light text-center mb-3">Просмотр настроек</h1>

    <div class="album py-5 bg-body-tertiary">
        <div class="container">
            <div class="row row-cols-1 row-cols-sm-2 row    -cols-md-3 g-3">
                {% for object in objects_list %}
                {% if perms.e_mail_app.view_mailingsettings or user == object.owner or user.is_superuser %}
                <div class="col">
                    <div class="card shadow-sm">
                        <div class="card-body">
                            <h1 class="card-title pricing-card-title">{{object.mailing_name}}</h1>
                            <p class="card-text">{{object.mail.message|slice:100}}...</p>
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">
                                    <a href="{% url 'e_mail_app:detail_settings' object.pk %}"
                                       class="btn btn-sm btn-outline-secondary">Просмотр</a>
                                    {% if user == object.owner or user.is_superuser or perms.e_mail_app.change_mailingsettings %}
                                    <a href="{% url 'e_mail_app:edit_settings' object.pk %}"
                                       class="btn btn-sm btn-outline-secondary">Изменить</a>
                                    {% endif %}
                                    {% if user == object.owner or user.is_superuser or perms.e_mail_app.delete_mailingsettings %}
                                    <a href="{% url 'e_mail_app:delete_settings' object.pk %}"
                                       class="btn btn-sm btn-outline-danger">Удалить</a>
                                    {% endif %}
                                    {% if perms.e_mail_app.toggle_active or user == object.owner or user.is_superuser %}
                                    {% if object.is_active %}
                                    <a href="{% url 'e_mail_app:activate_settings' object.pk %}"
                                       class="btn btn-sm btn-outline-danger">Отключить</a>
                                    {% else %}
                                    <a href="{% url 'e_mail_app:activate_settings' object.pk %}"
                                       class="btn btn-sm btn-outline-success">Активировать</a>
                                    {% endif %}
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>
                {% endif %}
                </div>
            {% endfor %}
            </div>

        </div>
    </div>
</main>
{% endif %}
{% endblock %}

e_mail_app/templates/mail_settings/settings_update_form.html
{% extends 'e_mail_app/base.html' %}
{% load static %}

{% block content %}
{% if user.is_blocked %}
<div class="col-12 text-center">
    <h1>
        Уважаемый пользователь, Ваш аккаунт заблокирован!
    </h1>
    <a class="p-2 btn btn-outline-primary" href="{% url 'users:logout' %}">Выйти</a>
</div>
{% else %}

<div class="container">
    <form method="post" action="" enctype="multipart/form-data" class="form-floating mx-auto">
        <div class="row ">
            <div class="col-12">
                <div class="col-10 mx-auto">
                <div class="card mb-4 box-shadow mx-auto">
                    <div class="card-header text-center">
                        <h4 class="my-0 font-weight-normal">Панель редактирования настроек рассылки</h4>
                    </div>
                    <div class="card-body text-center">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-block btn-outline-primary">Сохранить</button>
                    </div>
                </div>
            </div>
            </div>
        </div>
    </form>
</div>
{% endif %}

{% endblock %}