blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import BlogView, BlogCreateView, BlogDetailView, BlogUpdateView, BlogDeleteView, toggle_published

app_name = BlogConfig.name

urlpatterns = [
    path('', BlogView.as_view(), name='home'),
    path('record/new/', BlogCreateView.as_view(), name='create_record'),
    path('view/<int:pk>/', cache_page(60)(BlogDetailView.as_view()), name='view_record'),
    path('edit/<int:pk>/', BlogUpdateView.as_view(), name='edit_record'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='delete_record'),
    path('published/<int:pk>/', toggle_published, name='change_published'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('e_mail_app.urls'), name='e_mail_app'),
    path('users/', include('users.urls'), name='users'),
    path('blog/', include('blog.urls'), name='blog')
]

blog/models.py
from django.db import models

from e_mail_app.models import NULLABLE


# Create your models here.

class Blog(models.Model):
    title = models.CharField(max_length=150, verbose_name='Заголовок', **NULLABLE)
    body = models.TextField(verbose_name='Содержимое', **NULLABLE)
    image = models.ImageField(upload_to='blog/', verbose_name='Изображение', **NULLABLE)
    views_count = models.IntegerField(default=0, verbose_name='Количество просмотров')
    publish_date = models.DateTimeField(verbose_name='Дата создания', auto_now_add=True)
    is_published = models.BooleanField(default=True, verbose_name='Опубликован')

    def __str__(self):
        return f'{self.title}: {self.views_count}, {self.publish_date}'

    class Meta:
        verbose_name = 'Запись'
        verbose_name_plural = 'Записи'
        permissions = [
            (
                'can_toggle_published',
                'изменить статус публикации'
            )
        ]

blog/forms.py
from django import forms

from blog.models import Blog

WORDS_BLACKLIST = ('казино', 'криптовалюта', 'крипта', 'биржа', 'наркотики' 'бесплатно',
                   'обман', 'полиция', 'терракт')


class RecordAddForm(forms.ModelForm):
    class Meta:
        model = Blog
        exclude = ('is_published', 'views_count')

    def clean_title(self):
        cleaned_data = self.cleaned_data.get('title')
        if cleaned_data in WORDS_BLACKLIST:
            raise forms.ValidationError('У-пс, заголовок записи в списке запрещённых слов')

        return cleaned_data

    def clean_body(self):
        cleaned_data = self.cleaned_data.get('body')
        if cleaned_data in WORDS_BLACKLIST:
            raise forms.ValidationError('У-пс, в содержании записи есть слова из списка запрещённых слов')

        return cleaned_data

blog/views.py
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView

from blog.forms import RecordAddForm
from blog.models import Blog
from e_mail_app.services import get_cache_mailing_active, get_mailing_count_from_cache, get_cache_unique_quantity


# Create your views here.

class BlogView(ListView):
    model = Blog
    template_name = 'blog/blog_list.html'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        context['mailing_quantity_active'] = get_cache_mailing_active()
        context['mailing_quantity'] = get_mailing_count_from_cache()
        context['clients_unique_quantity'] = get_cache_unique_quantity()
        context['records'] = Blog.objects.order_by('?')[:3]

        return context


class BlogCreateView(CreateView):
    model = Blog
    template_name = 'blog/blog_form.html'
    form_class = RecordAddForm
    success_url = reverse_lazy('blog:home')


class BlogDetailView(DetailView):
    model = Blog
    template_name = 'blog/blog_detail.html'
    context_object_name = 'objects_list'

    def get_object(self, queryset=None):
        self.object = super().get_object()
        self.object.views_count += 1
        self.object.save()
        return self.object


class BlogUpdateView(UpdateView):
    model = Blog
    template_name = 'blog/blog_update_form.html'
    form_class = RecordAddForm
    success_url = reverse_lazy('blog:view_record')


class BlogDeleteView(DeleteView):
    model = Blog
    template_name = 'blog/blog_confirm_delete.html'
    success_url = reverse_lazy('blog:home')


def toggle_published(request, pk):
    record_item = get_object_or_404(Blog, pk=pk)
    if record_item.is_published:
        record_item.is_published = False
    else:
        record_item.is_published = True

    record_item.save()

    return redirect(reverse('blog:home'))

blog/templates/blog/blog_confirm_delete.html
{% extends 'e_mail_app/base.html' %}

{% block content %}
{% if user.is_blocked %}
<div class="col-12 text-center">
    <h1>
        Уважаемый пользователь, Ваш аккаунт заблокирован!
    </h1>
    <a class="p-2 btn btn-outline-primary" href="{% url 'users:logout' %}">Выйти</a>
</div>
{% else %}
<div class="col-12">
  <div class="row">
    <div class="col-6">
      <div class="card">
        <div class="card-body">
          <form method="post">
            {% csrf_token %}
            <p>Хотите удалить запись "{{object.title}}" ?</p>
            <button type="submit" class="btn btn-danger">Потвердить</button>
            <a href="{% url 'blog:home' %}" class="btn btn-success">Отмена</a>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endif %}
{% endblock %}

blog/templates/blog/blog_detail.html
{% extends 'e_mail_app/base.html' %}
{% load static %}
{% load image_tag %}


{% block content %}
{% if user.is_blocked %}
<div class="col-12 text-center">
    <h1>
        Уважаемый пользователь, Ваш аккаунт заблокирован!
    </h1>
    <a class="p-2 btn btn-outline-primary" href="{% url 'users:logout' %}">Выйти</a>
</div>
{% else %}
<h1 align="center">{{object.title}}</h1>
<p>{{object.body}}</p>
<div align="center">
    {% if object.image %}
    <img src="{% image_tag object.image %}" alt="404 но мы уже чиним..">
    {% endif %}
</div>
<p align="right">
    Количество просмотров: {{object.views_count}}
</p>
<div align="center">
    <a href="{% url 'blog:home' %}" class="btn btn-block btn-outline-danger">Назад</a>
</div>
{% endif %}
{% endblock %}

blog/templates/blog/blog_form.html
{% extends 'e_mail_app/base.html' %}

{% block content %}
{% if user.is_blocked %}
<div class="col-12 text-center">
    <h1>
        Уважаемый пользователь, Ваш аккаунт заблокирован!
    </h1>
    <a class="p-2 btn btn-outline-primary" href="{% url 'users:logout' %}">Выйти</a>
</div>
{% else %}
<div class="row mx-auto">
    <div class="col-6 mx-auto">
        <div class="card">
            <div class="card-body text-center">
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    {% if object.is_published %}
                    <button type="submit" class="btn btn-success">Сохранить</button>
                    {% else %}
                    <button type="submit" class="btn btn-success">Создать</button>
                    {% endif %}
                </form>
            </div>
        </div>
    </div>
</div>
{% endif %}

{% endblock %}

blog/templates/blog/blog_list.html
{% extends 'e_mail_app/base.html' %}
{% load static %}
{% load image_tag %}

{% block content %}
{% if user.is_blocked %}
<div class="col-12 text-center">
    <h1>
        Уважаемый пользователь, Ваш аккаунт заблокирован!
    </h1>
    <a class="p-2 btn btn-outline-primary" href="{% url 'users:logout' %}">Выйти</a>
</div>
{% else %}
<section class="py-5 text-center container">
    <div class="row py-lg-5">
        <div class="col-lg-6 col-md-8 mx-auto">
            <h1 class="fw-light">ЯРассылки</h1>
            <p class="lead text-body-secondary">Удобный сервис создания и отправки рассылок. Попробуй сейчас</p>
            <p>
                {% if perms.blog.add_blog or user.is_superuser %}
                <a href="{% url 'blog:create_record' %}" class="btn btn-primary my-2">Добавить блоговую запись</a>
                {% endif %}
            </p>
        </div>
    </div>
</section>
<div class="container">
    <div class="row text-left">
        <h3>Активных рассылок на данный момент: {{mailing_quantity_active}}</h3>
        <h3>Всего рассылок на данный момент: {{mailing_quantity}}</h3>
        <h3>Уникальных клиентов на данный момент: {{clients_unique_quantity}}</h3>
    </div>
    <div class="row text-center">
        {% for object in records %}
        <div class="col-3">
            <div class="card">
                {% if object.image %}
                <img src="#" class="card-img-top" alt="404 но мы уже чиним...">
                {% endif %}
                <div class="card-body">
                    <h5 class="card-title">{{object.title}}</h5>
                    <p class="card-text">{{object.body|slice:100}}</p>
                    <a class="btn btn-block btn-outline-primary" href="{% url 'blog:view_record' object.pk %}" role="button">Прочесть
                        полностью</a>
                    {% if perms.blog.change_blog and perms.blog.delete_blog or user.is_superuser %}
                    <button class="btn btn-primary" type="button" data-bs-toggle="collapse"
                            data-bs-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
                        Действия
                    </button>
                    <div class="collapse" id="collapseExample">
                        <div class="card card-body">
                            {% if perms.blog.change_blog or user.is_superuser %}
                            <a class="btn btn-block btn btn-primary" href="{% url 'blog:edit_record' object.pk %}" role="button">Редактировать</a>
                            {% if perms.blog.can_toggle_published or user.is_superuser %}
                            {% if object.is_published %}
                            <a class="btn btn-block btn btn-warning" href="{% url 'blog:change_published' object.pk %}" role="button">Снять
                                с публикации</a>
                            {% else %}
                            <a class="btn btn-block btn btn-success" href="{% url 'blog:change_published' object.pk %}" role="button">Опубликовать</a>
                            {% endif %}
                            {% endif %}
                            {% if perms.blog.delete_blog or user.is_superuser %}
                            <a class="btn btn-block btn btn-danger" href="{% url 'blog:delete_record' object.pk %}"
                               role="button">Удалить</a>
                            {% endif %}
                            {% endif %}
                        </div>
                    </div>
                    {% endif %}
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endif %}
{% endblock %}

blog/templates/blog/blog_update_form.html
{% extends 'e_mail_app/base.html' %}

{% block content %}
{% if user.is_blocked %}
<div class="col-12 text-center">
    <h1>
        Уважаемый пользователь, Ваш аккаунт заблокирован!
    </h1>
    <a class="p-2 btn btn-outline-primary" href="{% url 'users:logout' %}">Выйти</a>
</div>
{% else %}
<div class="row">
    <div class="col-6">
        <div class="card">
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">Сохранить</button>
                    <a href="{% url 'blog:home' %}" class="btn btn-danger">Отмена</a>
                </form>
            </div>
        </div>
    </div>
</div>
{% endif %}

{% endblock %}